ALTER TABLE [dbo].[STUDENT]
ADD CONSTRAINT [FK_STUDENT_COURSE] FOREIGN KEY ([COURSE]) REFERENCES [COURSE]([Title]);

ALTER TABLE [dbo].[COURSE] 
ADD CONSTRAINT [FK_COURSE_FACULTY] FOREIGN KEY ([FACULTY]) REFERENCES [FACULTY]([Title]);

ALTER TABLE [dbo].[TEACHER]
ADD CONSTRAINT [FK_TEACHER_FACULTY] FOREIGN KEY ([FACULTY]) REFERENCES [FACULTY]([Title]);

ALTER TABLE [dbo].[COURSESUBJECTS]
ADD CONSTRAINT [FK_COURSESUBJECTS_COURSE] FOREIGN KEY ([COURSE]) REFERENCES [COURSE]([Title]),
	CONSTRAINT [FK_COURSESUBJECTS_SUBJECT] FOREIGN KEY ([SUBJECT]) REFERENCES [SUBJECT]([Title]);

ALTER TABLE [dbo].[SUBJECTTEACHERS]
ADD CONSTRAINT [FK_COURSESUBJECTS_SUBJECT] FOREIGN KEY ([SUBJECT]) REFERENCES [SUBJECT]([Title]),
	CONSTRAINT [FK_COURSESUBJECTS_TEACHER] FOREIGN KEY ([TEACHER]) REFERENCES [TEACHER]([Title]);
