CREATE TABLE [dbo].[STUDENT]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL, 
	[COURSE] VARCHAR(50) NULL
);

CREATE TABLE [dbo].[COURSE] 
(
	[Title] VARCHAR(50) NOT NULL PRIMARY KEY,
	[EnrolledTotal] INT NULL,
	[FACULTY] VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[SUBJECT]
(
	[Title] VARCHAR(50) NOT NULL PRIMARY KEY,
	[AvgGrade] INT NULL
);

CREATE TABLE [dbo].[TEACHER]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL,
	[FACULTY] VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[FACULTY]
(
	[Title] VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE [dbo].[COURSESUBJECTS]
(
	[COURSE] VARCHAR(50) NOT NULL,
	[SUBJECT] VARCHAR(50) NOT NULL

	PRIMARY KEY (COURSE, SUBJECT)
);

CREATE TABLE [dbo].[SUBJECTTEACHERS]
(
	[SUBJECT] VARCHAR(50) NOT NULL,
	[TEACHER] INT NOT NULL

	PRIMARY KEY (SUBJECT, TEACHER)
);
